### ISSUE TITLE
Add Lydian support

### ISSUE THREAD

**Issue by pamputt** [googlei18n/noto-source#22] opened 2016-10-12 19:52 UTC
I installed all Google Noto Fonts and Firefox still does not support the display of Lydian. See for example https://en.wikipedia.org/wiki/Lydian_%28Unicode_block%29

**Comment by pamputt** [comment] 2016-10-12 20:12
Actually the problem of display only happens on Firefox. Characters are correctly displayed with Chromium 53

**Comment by marekjez86** [comment] 2016-11-08 17:14
The problem is with Firefox rendering engine. Closing the issue.

**Closed by marekjez86** 2016-11-08 17:14 UTC
