### ISSUE TITLE
AE ARABIC LETTER not joined with what comes before

### ISSUE THREAD

**Issue by pupyc** [googlei18n/noto-source#115] opened 2018-03-31 19:41 UTC
Character: ە
Name: ARABIC LETTER AE (U+06D5)
Uighur, Kurdish, Kazakh, Kirghiz,
UTF-8: 0xDB 0x95
UTF-16: 0x06D5
C octal escaped UTF-8: \333\225
`XML decimal entity: &#1749;`

Noto Sans Arabic

![noto-sans-arabic-ae](https://user-images.githubusercontent.com/31791780/38166782-168b837a-3519-11e8-8ead-a1abd25f5f81.png)

---

Noto Naskh Arabic

![noto-naskh-arabic-ae](https://user-images.githubusercontent.com/31791780/38166783-186decf0-3519-11e8-91c6-a8419cf1041f.png)

---

Amiri

![amiri-ae](https://user-images.githubusercontent.com/31791780/38166784-1a5d41fa-3519-11e8-82a2-6195d5a0fa2b.png)

**Comment by nizarsq** [comment] 2018-07-03 18:39
This issue is a duplicate of notofonts/arabic#69

**Comment by marekjez86** [comment] 2018-07-09 19:31
Keeping https://github.com/googlei18n/noto-fonts/issues/1017 open. Closing this issue

**Closed by marekjez86** 2018-07-09 19:31 UTC
Labels: duplicate
